language: csharp

os: linux
sudo: required
dist: trusty
dotnet: 1.0.1
env: DOTNETCORE=1
mono: none

script:
  # Build the source
  - cd src/Whathecode.System
  - dotnet restore
  - dotnet build
  
  # Back to main
  - cd ../../
  
  # Run tests
  - cd test/Whathecode.System.Tests
  - dotnet restore
  - dotnet test