language: csharp
solution: NET-Standard-Library-Extension.sln

dotnet: 1.0.0-preview2-003131
mono: none
env: DOTNETCORE=1

script:
  # Build the source
  - cd src/Whathecode.System
  - dotnet restore
  - dotnet build
  
  # Back to main
  - cd ../../
  
  # Run tests
  - cd test/Whathecode.System.Tests
  - dotnet restore
  - dotnet test